# Generated by Django 3.0.4 on 2020-03-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0001_firstVersionOfModels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='cloth',
        ),
        migrations.AddField(
            model_name='detailedclothes',
            name='colors',
            field=models.ManyToManyField(to='ClothesSearchApp.Color'),
        ),
        migrations.AddField(
            model_name='detailedclothes',
            name='img_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
