# Generated by Django 3.0.4 on 2020-03-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0003_added_clothes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detailedclothes',
            name='colors',
        ),
        migrations.AddField(
            model_name='clothes',
            name='colors',
            field=models.ManyToManyField(to='ClothesSearchApp.Color'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='sizes',
            field=models.ManyToManyField(to='ClothesSearchApp.Size'),
        ),
    ]
