# Generated by Django 3.0.4 on 2020-03-18 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0006_choices_in_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(choices=[('T-SHIRT', 'T-Shirty'), ('SHIRT', 'Koszule'), ('PANTS', 'Spodnie'), ('SHORTS', 'Szorty'), ('JACKET', 'Marynarki'), ('SWEATER', 'Swetry')], max_length=10)),
                ('colors', models.ManyToManyField(to='ClothesSearchApp.Color')),
            ],
        ),
        migrations.DeleteModel(
            name='TypeColors',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClothesSearchApp.Type'),
        ),
    ]
