# Generated by Django 3.0.4 on 2020-03-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0007_type_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='cloth_type',
            new_name='name',
        ),
    ]
