# Generated by Django 3.0.4 on 2020-03-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0008_type_quick_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedclothes',
            name='img_link',
        ),
        migrations.AddField(
            model_name='clothes',
            name='img_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='detailedclothes',
            name='composition',
            field=models.CharField(default='', max_length=200),
        ),
    ]
