# Generated by Django 3.0.4 on 2020-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0009_refactor_of_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='page_link',
            field=models.URLField(default=''),
        ),
    ]
