# Generated by Django 3.0.4 on 2020-04-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0010_added_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='img_link',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='page_link',
            field=models.URLField(default='', max_length=300),
        ),
    ]
