# Generated by Django 3.0.4 on 2020-04-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0011_change_max_length_of_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedclothes',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
