# Generated by Django 3.0.4 on 2020-04-06 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClothesSearchApp', '0013_raise_of_max_description_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothesSearchApp.Color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothesSearchApp.Size')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothesSearchApp.Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
