# Generated by Django 3.1.2 on 2020-10-10 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClothesSearchApp', '0015_add_key_field_to_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClothesSearchApp.color'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClothesSearchApp.size'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClothesSearchApp.type'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
