# Generated by Django 3.1.2 on 2020-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothesSearchApp', '0016_auto_20201010_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
